export const dataAboutBooks = [
  {
    id: 1,
    cover: "/card/covers/1",
    name: "The Chronicles of Narnia",
    author: "C. S. Lewis",
    rate: 4,
    price: "14,99",
  },
  {
    id: 8,
    cover: "/card/covers/2",
    name: "The Psychlogy of Money",
    author: "C. S. Bragich",
    rate: 5,
    price: "3",
  },
  {
    id: 2,
    cover: "/card/covers/3",
    name: "The Subtle art of not giving a fuck",
    author: "C. S. Lewis",
    rate: 4,
    price: "14,99",
  },
  {
    id: 3,
    cover: "/card/covers/1",
    name: "The Psychlogy of Money",
    author: "C. S. Bragich",
    rate: 5,
    price: "3",
  },
  {
    id: 4,
    cover: "/card/covers/1",
    name: "The Subtle art of not giving a fuck",
    author: "C. S. Olega",
    rate: 4,
    price: "14,99",
  },
  {
    id: 5,
    cover: "/card/covers/3",
    name: "The Psychlogy of Money",
    author: "C. S. Bragich",
    rate: 5,
    price: "3",
  },
  {
    id: 6,
    cover: "/card/covers/2",
    name: "The Chronicles of Narnia",
    author: "C. S. Bonjornou",
    rate: 1,
    price: "14,99",
  },
  {
    id: 7,
    cover: "/card/covers/2",
    name: "The Psychlogy of Money",
    author: "C. S. Bragich",
    rate: 3,
    price: "3",
  },
];
